const SET_TODOS = "SET_TODOS";
const ADD_NEW_TODO = "ADD_NEW_TODO";
const UPDATE_TODO = "UPDATE_TODO";
const DELETE_TODO = "DELETE_TODO";

const SET_BUCKETS = "SET_BUCKETS";

export { SET_TODOS, ADD_NEW_TODO, UPDATE_TODO, DELETE_TODO, SET_BUCKETS };
